#!/bin/sh

# This is a example init.d script
# - Set yours variables
# - Place this script into /etc/init.d
# - Add to startup running: sudo update-rc.d mplayerjs defaults

set -e

NAME="$0"
PIDFILE=/var/run/$NAME.pid
USER=ubuntu
DAEMON=/usr/bin/node
DAEMON_OPTS="/home/ubuntu/experiment/client.js"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        start-stop-daemon --start --quiet --pidfile $PIDFILE -b -u $USER --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        echo "."
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;

  *)
        echo "Usage: "$1" {start|stop|restart}"
        exit 1
esac

exit 0
